PODMAN=${XDG_DATA_HOME}/podman-dist/current/usr/local/bin/podman
PATH=${XDG_DATA_HOME}/podman-dist/current/usr/local/libexec/podman:${XDG_DATA_HOME}/podman-dist/current/usr/local/lib/podman:${XDG_DATA_HOME}/podman-dist/current/usr/local/bin:${PATH}
QUADLET_UNIT_DIRS=${XDG_CONFIG_HOME:-$HOME/.config}/containers-quadlet
