// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (mountpoint_id, path, dev, ino)
VALUES ($1, $2, $3, $4)
RETURNING id, mountpoint_id, path, dev, ino, current_content_version_id, deleted_at, first_seen_at, updated_at
`

type CreateDocumentParams struct {
	MountpointID int64
	Path         string
	Dev          int64
	Ino          int64
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.MountpointID,
		arg.Path,
		arg.Dev,
		arg.Ino,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDocumentSourcePath = `-- name: FindDocumentSourcePath :one
SELECT d.path, o.size
FROM documents d
JOIN fs_observations o
  ON o.mountpoint_id = d.mountpoint_id AND o.path = d.path
WHERE d.id = $1
  AND d.current_content_version_id = $2
  AND d.deleted_at IS NULL
`

type FindDocumentSourcePathParams struct {
	ID                      int64
	CurrentContentVersionID *int64
}

type FindDocumentSourcePathRow struct {
	Path string
	Size int64
}

// FindDocumentSourcePath is the render path's file lookup. It takes both halves
// of the ref rather than the content version alone: content is deduplicated by
// hash, so one version is legitimately current for several documents, and
// resolving by version would stream whichever of them sorted first — a file the
// caller never named. Requiring the version to still be the document's current
// one makes a superseded ref yield no row instead of the wrong bytes, and the
// fs_observations join keeps a document whose file has since disappeared from
// yielding a path that fails to open.
func (q *Queries) FindDocumentSourcePath(ctx context.Context, arg FindDocumentSourcePathParams) (FindDocumentSourcePathRow, error) {
	row := q.db.QueryRow(ctx, findDocumentSourcePath, arg.ID, arg.CurrentContentVersionID)
	var i FindDocumentSourcePathRow
	err := row.Scan(&i.Path, &i.Size)
	return i, err
}

const findLiveDocumentByContent = `-- name: FindLiveDocumentByContent :one
SELECT d.id, d.mountpoint_id, d.path, d.dev, d.ino, d.current_content_version_id, d.deleted_at, d.first_seen_at, d.updated_at FROM documents d
JOIN content_versions cv ON cv.id = d.current_content_version_id
WHERE d.mountpoint_id = $1
  AND cv.content_hash = $2
  AND d.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM fs_observations o
      WHERE o.mountpoint_id = d.mountpoint_id AND o.path = d.path
  )
ORDER BY d.id
LIMIT 1
`

type FindLiveDocumentByContentParams struct {
	MountpointID int64
	ContentHash  string
}

// FindLiveDocumentByContent only considers documents whose own path no longer
// exists as an observation; otherwise a plain copy of a file would be mistaken
// for a move of it.
func (q *Queries) FindLiveDocumentByContent(ctx context.Context, arg FindLiveDocumentByContentParams) (Document, error) {
	row := q.db.QueryRow(ctx, findLiveDocumentByContent, arg.MountpointID, arg.ContentHash)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLiveDocumentByInode = `-- name: FindLiveDocumentByInode :one
SELECT id, mountpoint_id, path, dev, ino, current_content_version_id, deleted_at, first_seen_at, updated_at FROM documents
WHERE mountpoint_id = $1
  AND dev = $2
  AND ino = $3
  AND deleted_at IS NULL
ORDER BY id
LIMIT 1
`

type FindLiveDocumentByInodeParams struct {
	MountpointID int64
	Dev          int64
	Ino          int64
}

func (q *Queries) FindLiveDocumentByInode(ctx context.Context, arg FindLiveDocumentByInodeParams) (Document, error) {
	row := q.db.QueryRow(ctx, findLiveDocumentByInode, arg.MountpointID, arg.Dev, arg.Ino)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLiveDocumentByPath = `-- name: FindLiveDocumentByPath :one

SELECT id, mountpoint_id, path, dev, ino, current_content_version_id, deleted_at, first_seen_at, updated_at FROM documents
WHERE mountpoint_id = $1 AND path = $2 AND deleted_at IS NULL
`

type FindLiveDocumentByPathParams struct {
	MountpointID int64
	Path         string
}

// Document identity (D-007), content versions, and extraction results.
//
// The indexer resolves identity in this order on a create/modify event:
//  1. FindLiveDocumentByPath   - the ordinary case, path unchanged;
//  2. FindLiveDocumentByInode  - same file, moved (inode survives a rename);
//  3. FindLiveDocumentByContent - inode changed but bytes did not, which is
//     what write-to-temp-then-rename editors produce;
//  4. CreateDocument.
func (q *Queries) FindLiveDocumentByPath(ctx context.Context, arg FindLiveDocumentByPathParams) (Document, error) {
	row := q.db.QueryRow(ctx, findLiveDocumentByPath, arg.MountpointID, arg.Path)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPathForContentVersion = `-- name: FindPathForContentVersion :one
SELECT d.id AS document_id, d.mountpoint_id, d.path, o.size
FROM documents d
JOIN fs_observations o
  ON o.mountpoint_id = d.mountpoint_id AND o.path = d.path
WHERE d.current_content_version_id = $1
  AND d.deleted_at IS NULL
ORDER BY d.id
LIMIT 1
`

type FindPathForContentVersionRow struct {
	DocumentID   int64
	MountpointID int64
	Path         string
	Size         int64
}

// FindPathForContentVersion resolves the bytes behind a content version back to
// a file the extractor can open. It joins fs_observations rather than trusting
// documents.path alone so a document whose file has since disappeared yields no
// row instead of a path that fails to open.
func (q *Queries) FindPathForContentVersion(ctx context.Context, contentVersionID *int64) (FindPathForContentVersionRow, error) {
	row := q.db.QueryRow(ctx, findPathForContentVersion, contentVersionID)
	var i FindPathForContentVersionRow
	err := row.Scan(
		&i.DocumentID,
		&i.MountpointID,
		&i.Path,
		&i.Size,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT
    d.id, d.mountpoint_id, d.path, d.dev, d.ino, d.current_content_version_id, d.deleted_at, d.first_seen_at, d.updated_at,
    m.root_path,
    cv.content_hash,
    cv.size_bytes,
    cv.created_at      AS content_first_seen_at,
    ec.status          AS extraction_status,
    ec.content_type,
    ec.metadata,
    -- "Stored and searchable", which is stricter than "not empty": a failed
    -- extraction keeps the text of the attempt before it (see
    -- MarkExtractionFailed), and SearchDocuments requires status = 'succeeded',
    -- so text left behind by a failure is present but unfindable. The status
    -- test is what keeps this column agreeing with what search will do.
    --
    -- COALESCE, because the LEFT JOIN yields NULL for a document with no
    -- extraction row at all, which is "no text" rather than an unknown.
    COALESCE(ec.status = 'succeeded' AND ec.text_normalized <> '', false)::boolean
        AS has_extracted_text,
    ec.error           AS extraction_error,
    ec.extracted_at
FROM documents d
JOIN mountpoints m ON m.id = d.mountpoint_id
LEFT JOIN content_versions cv ON cv.id = d.current_content_version_id
LEFT JOIN extracted_contents ec ON ec.content_version_id = cv.id
WHERE d.id = $1
`

type GetDocumentRow struct {
	ID                      int64
	MountpointID            int64
	Path                    string
	Dev                     int64
	Ino                     int64
	CurrentContentVersionID *int64
	DeletedAt               pgtype.Timestamptz
	FirstSeenAt             pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	RootPath                string
	ContentHash             *string
	SizeBytes               *int64
	ContentFirstSeenAt      pgtype.Timestamptz
	ExtractionStatus        *string
	ContentType             *string
	Metadata                []byte
	HasExtractedText        bool
	ExtractionError         *string
	ExtractedAt             pgtype.Timestamptz
}

// GetDocument is the API's detail read as well as its version check: the
// content hash it returns is the content_version_id every render is addressed
// by, so one row answers both "does this document exist" and "is this ref
// still current".
//
// root_path comes along because the API reports a path relative to the
// mountpoint while documents.path is absolute.
func (q *Queries) GetDocument(ctx context.Context, id int64) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
		&i.RootPath,
		&i.ContentHash,
		&i.SizeBytes,
		&i.ContentFirstSeenAt,
		&i.ExtractionStatus,
		&i.ContentType,
		&i.Metadata,
		&i.HasExtractedText,
		&i.ExtractionError,
		&i.ExtractedAt,
	)
	return i, err
}

const getDocumentText = `-- name: GetDocumentText :one
SELECT ec.text_normalized
FROM documents d
JOIN extracted_contents ec ON ec.content_version_id = d.current_content_version_id
WHERE d.id = $1
`

func (q *Queries) GetDocumentText(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getDocumentText, id)
	var text_normalized string
	err := row.Scan(&text_normalized)
	return text_normalized, err
}

const getExtraction = `-- name: GetExtraction :one
SELECT content_version_id, status, text_normalized, metadata, content_type, error, extracted_at, updated_at FROM extracted_contents WHERE content_version_id = $1
`

func (q *Queries) GetExtraction(ctx context.Context, contentVersionID int64) (ExtractedContent, error) {
	row := q.db.QueryRow(ctx, getExtraction, contentVersionID)
	var i ExtractedContent
	err := row.Scan(
		&i.ContentVersionID,
		&i.Status,
		&i.TextNormalized,
		&i.Metadata,
		&i.ContentType,
		&i.Error,
		&i.ExtractedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markExtractionFailed = `-- name: MarkExtractionFailed :exec
INSERT INTO extracted_contents (content_version_id, status, error)
VALUES ($1, 'failed', $2)
ON CONFLICT (content_version_id) DO UPDATE SET
    status     = 'failed',
    error      = EXCLUDED.error,
    updated_at = now()
`

type MarkExtractionFailedParams struct {
	ContentVersionID int64
	Error            *string
}

// MarkExtractionFailed records why extraction failed and leaves
// text_normalized and extracted_at as they were. The row drops out of search
// either way because SearchDocuments requires status = 'succeeded'; keeping the
// old text means a later success can be compared against it rather than
// appearing out of nowhere.
func (q *Queries) MarkExtractionFailed(ctx context.Context, arg MarkExtractionFailedParams) error {
	_, err := q.db.Exec(ctx, markExtractionFailed, arg.ContentVersionID, arg.Error)
	return err
}

const markExtractionPending = `-- name: MarkExtractionPending :exec
INSERT INTO extracted_contents (content_version_id, status)
VALUES ($1, 'pending')
ON CONFLICT (content_version_id) DO NOTHING
`

// MarkExtractionPending claims a content version for extraction without
// disturbing a result already there, so re-enqueueing a job cannot blank out
// text that is still correct while the retry is in flight.
func (q *Queries) MarkExtractionPending(ctx context.Context, contentVersionID int64) error {
	_, err := q.db.Exec(ctx, markExtractionPending, contentVersionID)
	return err
}

const moveDocument = `-- name: MoveDocument :one
UPDATE documents
SET path = $1, dev = $2, ino = $3, updated_at = now()
WHERE id = $4
RETURNING id, mountpoint_id, path, dev, ino, current_content_version_id, deleted_at, first_seen_at, updated_at
`

type MoveDocumentParams struct {
	Path string
	Dev  int64
	Ino  int64
	ID   int64
}

func (q *Queries) MoveDocument(ctx context.Context, arg MoveDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, moveDocument,
		arg.Path,
		arg.Dev,
		arg.Ino,
		arg.ID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveDocumentSubtree = `-- name: MoveDocumentSubtree :many
UPDATE documents
SET path = $1 || substr(path, length($2::text) + 1),
    updated_at = now()
WHERE mountpoint_id = $3
  AND starts_with(path, $2)
  AND deleted_at IS NULL
RETURNING id, path
`

type MoveDocumentSubtreeParams struct {
	NewPrefix    string
	OldPrefix    string
	MountpointID int64
}

type MoveDocumentSubtreeRow struct {
	ID   int64
	Path string
}

// MoveDocumentSubtree re-paths every live document under a renamed directory.
// go-overwatch reports a directory rename as one Move event and emits nothing
// for the files inside it, so without this the whole subtree would keep paths
// that no longer exist and D-007's identity-across-moves guarantee would hold
// for files but not for the directories containing them.
func (q *Queries) MoveDocumentSubtree(ctx context.Context, arg MoveDocumentSubtreeParams) ([]MoveDocumentSubtreeRow, error) {
	rows, err := q.db.Query(ctx, moveDocumentSubtree, arg.NewPrefix, arg.OldPrefix, arg.MountpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MoveDocumentSubtreeRow
	for rows.Next() {
		var i MoveDocumentSubtreeRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentCurrentVersion = `-- name: SetDocumentCurrentVersion :one
UPDATE documents
SET current_content_version_id = $1, updated_at = now()
WHERE id = $2
RETURNING id, mountpoint_id, path, dev, ino, current_content_version_id, deleted_at, first_seen_at, updated_at
`

type SetDocumentCurrentVersionParams struct {
	CurrentContentVersionID *int64
	ID                      int64
}

func (q *Queries) SetDocumentCurrentVersion(ctx context.Context, arg SetDocumentCurrentVersionParams) (Document, error) {
	row := q.db.QueryRow(ctx, setDocumentCurrentVersion, arg.CurrentContentVersionID, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tombstoneDocument = `-- name: TombstoneDocument :one
UPDATE documents
SET deleted_at = COALESCE(deleted_at, now()), updated_at = now()
WHERE id = $1
RETURNING id, mountpoint_id, path, dev, ino, current_content_version_id, deleted_at, first_seen_at, updated_at
`

func (q *Queries) TombstoneDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRow(ctx, tombstoneDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tombstoneDocumentByPath = `-- name: TombstoneDocumentByPath :one
UPDATE documents
SET deleted_at = COALESCE(deleted_at, now()), updated_at = now()
WHERE mountpoint_id = $1 AND path = $2 AND deleted_at IS NULL
RETURNING id, mountpoint_id, path, dev, ino, current_content_version_id, deleted_at, first_seen_at, updated_at
`

type TombstoneDocumentByPathParams struct {
	MountpointID int64
	Path         string
}

func (q *Queries) TombstoneDocumentByPath(ctx context.Context, arg TombstoneDocumentByPathParams) (Document, error) {
	row := q.db.QueryRow(ctx, tombstoneDocumentByPath, arg.MountpointID, arg.Path)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MountpointID,
		&i.Path,
		&i.Dev,
		&i.Ino,
		&i.CurrentContentVersionID,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tombstoneDocumentSubtree = `-- name: TombstoneDocumentSubtree :many
UPDATE documents
SET deleted_at = COALESCE(deleted_at, now()), updated_at = now()
WHERE mountpoint_id = $1
  AND starts_with(path, $2)
  AND deleted_at IS NULL
RETURNING id, path, current_content_version_id
`

type TombstoneDocumentSubtreeParams struct {
	MountpointID int64
	PathPrefix   string
}

type TombstoneDocumentSubtreeRow struct {
	ID                      int64
	Path                    string
	CurrentContentVersionID *int64
}

// The content version comes back with each row because tombstoning is what
// makes a version stale: the caller turns each one into an invalidation job.
func (q *Queries) TombstoneDocumentSubtree(ctx context.Context, arg TombstoneDocumentSubtreeParams) ([]TombstoneDocumentSubtreeRow, error) {
	rows, err := q.db.Query(ctx, tombstoneDocumentSubtree, arg.MountpointID, arg.PathPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TombstoneDocumentSubtreeRow
	for rows.Next() {
		var i TombstoneDocumentSubtreeRow
		if err := rows.Scan(&i.ID, &i.Path, &i.CurrentContentVersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContentVersion = `-- name: UpsertContentVersion :one
INSERT INTO content_versions (content_hash, size_bytes)
VALUES ($1, $2)
ON CONFLICT (content_hash) DO UPDATE SET size_bytes = EXCLUDED.size_bytes
RETURNING id, content_hash, size_bytes, created_at
`

type UpsertContentVersionParams struct {
	ContentHash string
	SizeBytes   int64
}

// UpsertContentVersion is hash-addressed, so two documents holding identical
// bytes converge on one row and reuse its extraction and thumbnails. The
// no-op UPDATE is there to make RETURNING fire on conflict.
func (q *Queries) UpsertContentVersion(ctx context.Context, arg UpsertContentVersionParams) (ContentVersion, error) {
	row := q.db.QueryRow(ctx, upsertContentVersion, arg.ContentHash, arg.SizeBytes)
	var i ContentVersion
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertExtraction = `-- name: UpsertExtraction :one
INSERT INTO extracted_contents (
    content_version_id, status, text_normalized, metadata, content_type, error, extracted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
ON CONFLICT (content_version_id) DO UPDATE SET
    status          = EXCLUDED.status,
    text_normalized = EXCLUDED.text_normalized,
    metadata        = EXCLUDED.metadata,
    content_type    = EXCLUDED.content_type,
    error           = EXCLUDED.error,
    extracted_at    = EXCLUDED.extracted_at,
    updated_at      = now()
RETURNING content_version_id, status, text_normalized, metadata, content_type, error, extracted_at, updated_at
`

type UpsertExtractionParams struct {
	ContentVersionID int64
	Status           string
	TextNormalized   string
	Metadata         []byte
	ContentType      *string
	Error            *string
}

func (q *Queries) UpsertExtraction(ctx context.Context, arg UpsertExtractionParams) (ExtractedContent, error) {
	row := q.db.QueryRow(ctx, upsertExtraction,
		arg.ContentVersionID,
		arg.Status,
		arg.TextNormalized,
		arg.Metadata,
		arg.ContentType,
		arg.Error,
	)
	var i ExtractedContent
	err := row.Scan(
		&i.ContentVersionID,
		&i.Status,
		&i.TextNormalized,
		&i.Metadata,
		&i.ContentType,
		&i.Error,
		&i.ExtractedAt,
		&i.UpdatedAt,
	)
	return i, err
}
