// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filesystem.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteObservation = `-- name: DeleteObservation :exec
DELETE FROM fs_observations WHERE mountpoint_id = $1 AND path = $2
`

type DeleteObservationParams struct {
	MountpointID int64
	Path         string
}

func (q *Queries) DeleteObservation(ctx context.Context, arg DeleteObservationParams) error {
	_, err := q.db.Exec(ctx, deleteObservation, arg.MountpointID, arg.Path)
	return err
}

const deleteObservationSubtree = `-- name: DeleteObservationSubtree :many
DELETE FROM fs_observations
WHERE mountpoint_id = $1 AND starts_with(path, $2)
RETURNING path
`

type DeleteObservationSubtreeParams struct {
	MountpointID int64
	PathPrefix   string
}

func (q *Queries) DeleteObservationSubtree(ctx context.Context, arg DeleteObservationSubtreeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteObservationSubtree, arg.MountpointID, arg.PathPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMountpointByRoot = `-- name: GetMountpointByRoot :one
SELECT id, root_path, enabled, created_at, updated_at FROM mountpoints WHERE root_path = $1
`

func (q *Queries) GetMountpointByRoot(ctx context.Context, rootPath string) (Mountpoint, error) {
	row := q.db.QueryRow(ctx, getMountpointByRoot, rootPath)
	var i Mountpoint
	err := row.Scan(
		&i.ID,
		&i.RootPath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getObservation = `-- name: GetObservation :one
SELECT mountpoint_id, path, size, mode, mtime, ino, dev, is_dir, seen_epoch, observed_at FROM fs_observations WHERE mountpoint_id = $1 AND path = $2
`

type GetObservationParams struct {
	MountpointID int64
	Path         string
}

func (q *Queries) GetObservation(ctx context.Context, arg GetObservationParams) (FsObservation, error) {
	row := q.db.QueryRow(ctx, getObservation, arg.MountpointID, arg.Path)
	var i FsObservation
	err := row.Scan(
		&i.MountpointID,
		&i.Path,
		&i.Size,
		&i.Mode,
		&i.Mtime,
		&i.Ino,
		&i.Dev,
		&i.IsDir,
		&i.SeenEpoch,
		&i.ObservedAt,
	)
	return i, err
}

const getWatermark = `-- name: GetWatermark :one
SELECT watermark FROM reconcile_state WHERE id
`

func (q *Queries) GetWatermark(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getWatermark)
	var watermark int64
	err := row.Scan(&watermark)
	return watermark, err
}

const listMountpoints = `-- name: ListMountpoints :many
SELECT id, root_path, enabled, created_at, updated_at FROM mountpoints ORDER BY root_path
`

func (q *Queries) ListMountpoints(ctx context.Context) ([]Mountpoint, error) {
	rows, err := q.db.Query(ctx, listMountpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mountpoint
	for rows.Next() {
		var i Mountpoint
		if err := rows.Scan(
			&i.ID,
			&i.RootPath,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWatermark = `-- name: LockWatermark :one
SELECT watermark FROM reconcile_state WHERE id FOR UPDATE
`

// LockWatermark is GetWatermark for the apply path, which must decide whether
// an event was already applied and write the new value without another applier
// interleaving between the two.
func (q *Queries) LockWatermark(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, lockWatermark)
	var watermark int64
	err := row.Scan(&watermark)
	return watermark, err
}

const moveObservationSubtree = `-- name: MoveObservationSubtree :exec
UPDATE fs_observations
SET path        = $1 || substr(path, length($2::text) + 1),
    observed_at = now()
WHERE mountpoint_id = $3 AND starts_with(path, $2)
`

type MoveObservationSubtreeParams struct {
	NewPrefix    string
	OldPrefix    string
	MountpointID int64
}

// MoveObservationSubtree re-paths a renamed directory's contents. It pairs with
// MoveDocumentSubtree: one Move event stands for every path beneath the
// directory, so the rows have to be rewritten rather than re-observed.
func (q *Queries) MoveObservationSubtree(ctx context.Context, arg MoveObservationSubtreeParams) error {
	_, err := q.db.Exec(ctx, moveObservationSubtree, arg.NewPrefix, arg.OldPrefix, arg.MountpointID)
	return err
}

const nextScanEpoch = `-- name: NextScanEpoch :one
SELECT nextval('scan_epoch_seq')
`

func (q *Queries) NextScanEpoch(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextScanEpoch)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}

const setWatermark = `-- name: SetWatermark :exec
UPDATE reconcile_state SET watermark = GREATEST(watermark, $1) WHERE id
`

func (q *Queries) SetWatermark(ctx context.Context, watermark int64) error {
	_, err := q.db.Exec(ctx, setWatermark, watermark)
	return err
}

const sweepScanEpoch = `-- name: SweepScanEpoch :many
DELETE FROM fs_observations
WHERE mountpoint_id = $1
  AND (path = $2 OR starts_with(path, $3))
  AND seen_epoch <> $4
RETURNING path
`

type SweepScanEpochParams struct {
	MountpointID int64
	Root         string
	RootPrefix   string
	SeenEpoch    int64
}

// SweepScanEpoch removes everything under a root that the current scan did not
// observe. That is how deletes missed during a subscribe gap are recovered.
func (q *Queries) SweepScanEpoch(ctx context.Context, arg SweepScanEpochParams) ([]string, error) {
	rows, err := q.db.Query(ctx, sweepScanEpoch,
		arg.MountpointID,
		arg.Root,
		arg.RootPrefix,
		arg.SeenEpoch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMountpoint = `-- name: UpsertMountpoint :one

INSERT INTO mountpoints (root_path, enabled)
VALUES ($1, $2)
ON CONFLICT (root_path) DO UPDATE SET
    enabled    = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, root_path, enabled, created_at, updated_at
`

type UpsertMountpointParams struct {
	RootPath string
	Enabled  bool
}

// Mountpoint registration and the go-overwatch reconciliation surface:
// observations, scan epochs, and the event watermark.
func (q *Queries) UpsertMountpoint(ctx context.Context, arg UpsertMountpointParams) (Mountpoint, error) {
	row := q.db.QueryRow(ctx, upsertMountpoint, arg.RootPath, arg.Enabled)
	var i Mountpoint
	err := row.Scan(
		&i.ID,
		&i.RootPath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertObservation = `-- name: UpsertObservation :exec
INSERT INTO fs_observations (
    mountpoint_id, path, size, mode, mtime, ino, dev, is_dir, seen_epoch, observed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, now()
)
ON CONFLICT (mountpoint_id, path) DO UPDATE SET
    size        = EXCLUDED.size,
    mode        = EXCLUDED.mode,
    mtime       = EXCLUDED.mtime,
    ino         = EXCLUDED.ino,
    dev         = EXCLUDED.dev,
    is_dir      = EXCLUDED.is_dir,
    seen_epoch  = EXCLUDED.seen_epoch,
    observed_at = now()
`

type UpsertObservationParams struct {
	MountpointID int64
	Path         string
	Size         int64
	Mode         int64
	Mtime        pgtype.Timestamptz
	Ino          int64
	Dev          int64
	IsDir        bool
	SeenEpoch    int64
}

func (q *Queries) UpsertObservation(ctx context.Context, arg UpsertObservationParams) error {
	_, err := q.db.Exec(ctx, upsertObservation,
		arg.MountpointID,
		arg.Path,
		arg.Size,
		arg.Mode,
		arg.Mtime,
		arg.Ino,
		arg.Dev,
		arg.IsDir,
		arg.SeenEpoch,
	)
	return err
}
