// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentVersion struct {
	ID          int64
	ContentHash string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

type Document struct {
	ID                      int64
	MountpointID            int64
	Path                    string
	Dev                     int64
	Ino                     int64
	CurrentContentVersionID *int64
	DeletedAt               pgtype.Timestamptz
	FirstSeenAt             pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type ExtractedContent struct {
	ContentVersionID int64
	Status           string
	TextNormalized   string
	Metadata         []byte
	ContentType      *string
	Error            *string
	ExtractedAt      pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type FsObservation struct {
	MountpointID int64
	Path         string
	Size         int64
	Mode         int64
	Mtime        pgtype.Timestamptz
	Ino          int64
	Dev          int64
	IsDir        bool
	SeenEpoch    int64
	ObservedAt   pgtype.Timestamptz
}

type Mountpoint struct {
	ID        int64
	RootPath  string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ReconcileState struct {
	ID        bool
	Watermark int64
}

type ThumbnailCache struct {
	ID               int64
	ContentVersionID int64
	Page             int32
	Width            int32
	Height           int32
	Format           string
	ObjectKey        string
	SizeBytes        int64
	CreatedAt        pgtype.Timestamptz
	LastAccessAt     pgtype.Timestamptz
	PendingDeleteAt  pgtype.Timestamptz
}
