// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thumbnails.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleThumbnails = `-- name: DeleteStaleThumbnails :many
DELETE FROM thumbnail_cache tc
WHERE NOT EXISTS (
    SELECT 1 FROM documents d
    WHERE d.current_content_version_id = tc.content_version_id
      AND d.deleted_at IS NULL
)
RETURNING tc.id, tc.object_key, tc.size_bytes
`

type DeleteStaleThumbnailsRow struct {
	ID        int64
	ObjectKey string
	SizeBytes int64
}

// DeleteStaleThumbnails drops accounting for every content version that is no
// longer any live document's current version: the modified-document case and
// the tombstoned-document case are the same query, because both stop the
// version from being current.
func (q *Queries) DeleteStaleThumbnails(ctx context.Context) ([]DeleteStaleThumbnailsRow, error) {
	rows, err := q.db.Query(ctx, deleteStaleThumbnails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteStaleThumbnailsRow
	for rows.Next() {
		var i DeleteStaleThumbnailsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteThumbnails = `-- name: DeleteThumbnails :many
DELETE FROM thumbnail_cache WHERE id = ANY($1::bigint[])
RETURNING id, object_key, size_bytes
`

type DeleteThumbnailsRow struct {
	ID        int64
	ObjectKey string
	SizeBytes int64
}

func (q *Queries) DeleteThumbnails(ctx context.Context, ids []int64) ([]DeleteThumbnailsRow, error) {
	rows, err := q.db.Query(ctx, deleteThumbnails, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteThumbnailsRow
	for rows.Next() {
		var i DeleteThumbnailsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteThumbnailsForStaleContentVersion = `-- name: DeleteThumbnailsForStaleContentVersion :many
DELETE FROM thumbnail_cache tc
WHERE tc.content_version_id = $1
  AND NOT EXISTS (
      SELECT 1 FROM documents d
      WHERE d.current_content_version_id = tc.content_version_id
        AND d.deleted_at IS NULL
  )
RETURNING tc.id, tc.object_key, tc.size_bytes
`

type DeleteThumbnailsForStaleContentVersionRow struct {
	ID        int64
	ObjectKey string
	SizeBytes int64
}

// DeleteThumbnailsForStaleContentVersion is the targeted form, run on the
// ingestion path with the version a document just stopped pointing at, so a
// changed document cannot serve a stale thumbnail before the sweep runs. The
// NOT EXISTS guard keeps it from evicting a version another live document still
// holds, which deduplicated content makes possible.
func (q *Queries) DeleteThumbnailsForStaleContentVersion(ctx context.Context, contentVersionID int64) ([]DeleteThumbnailsForStaleContentVersionRow, error) {
	rows, err := q.db.Query(ctx, deleteThumbnailsForStaleContentVersion, contentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteThumbnailsForStaleContentVersionRow
	for rows.Next() {
		var i DeleteThumbnailsForStaleContentVersionRow
		if err := rows.Scan(&i.ID, &i.ObjectKey, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThumbnail = `-- name: GetThumbnail :one
SELECT id, content_version_id, page, width, height, format, object_key, size_bytes, created_at, last_access_at FROM thumbnail_cache
WHERE content_version_id = $1
  AND page = $2
  AND width = $3
  AND height = $4
  AND format = $5
`

type GetThumbnailParams struct {
	ContentVersionID int64
	Page             int32
	Width            int32
	Height           int32
	Format           string
}

func (q *Queries) GetThumbnail(ctx context.Context, arg GetThumbnailParams) (ThumbnailCache, error) {
	row := q.db.QueryRow(ctx, getThumbnail,
		arg.ContentVersionID,
		arg.Page,
		arg.Width,
		arg.Height,
		arg.Format,
	)
	var i ThumbnailCache
	err := row.Scan(
		&i.ID,
		&i.ContentVersionID,
		&i.Page,
		&i.Width,
		&i.Height,
		&i.Format,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.LastAccessAt,
	)
	return i, err
}

const thumbnailEvictionCandidatesByAge = `-- name: ThumbnailEvictionCandidatesByAge :many
SELECT id, object_key, size_bytes, created_at, last_access_at
FROM thumbnail_cache
WHERE created_at < $1
ORDER BY created_at
LIMIT $2
`

type ThumbnailEvictionCandidatesByAgeParams struct {
	OlderThan   pgtype.Timestamptz
	ResultLimit int32
}

type ThumbnailEvictionCandidatesByAgeRow struct {
	ID           int64
	ObjectKey    string
	SizeBytes    int64
	CreatedAt    pgtype.Timestamptz
	LastAccessAt pgtype.Timestamptz
}

func (q *Queries) ThumbnailEvictionCandidatesByAge(ctx context.Context, arg ThumbnailEvictionCandidatesByAgeParams) ([]ThumbnailEvictionCandidatesByAgeRow, error) {
	rows, err := q.db.Query(ctx, thumbnailEvictionCandidatesByAge, arg.OlderThan, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThumbnailEvictionCandidatesByAgeRow
	for rows.Next() {
		var i ThumbnailEvictionCandidatesByAgeRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.LastAccessAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const thumbnailEvictionCandidatesByQuota = `-- name: ThumbnailEvictionCandidatesByQuota :many
SELECT
    t.id,
    t.object_key,
    t.size_bytes,
    (
        SELECT COALESCE(sum(t2.size_bytes), 0)
        FROM thumbnail_cache t2
        WHERE (t2.last_access_at, t2.id) >= (t.last_access_at, t.id)
    )::bigint AS running_bytes
FROM thumbnail_cache t
WHERE (
    SELECT COALESCE(sum(t2.size_bytes), 0)
    FROM thumbnail_cache t2
    WHERE (t2.last_access_at, t2.id) >= (t.last_access_at, t.id)
) > $1
ORDER BY t.last_access_at ASC, t.id ASC
`

type ThumbnailEvictionCandidatesByQuotaRow struct {
	ID           int64
	ObjectKey    string
	SizeBytes    int64
	RunningBytes int64
}

// ThumbnailEvictionCandidatesByQuota returns the LRU tail that pushes the cache
// over max_bytes: running_bytes accumulates newest-accessed first, so the rows
// kept are the most recently used and the rows returned are exactly the
// overflow, oldest first.
//
// Written as a correlated subtotal rather than the equivalent
// `sum(...) OVER (...)` because sqlc cannot resolve a window function's output
// column when it is referenced from an enclosing WHERE.
func (q *Queries) ThumbnailEvictionCandidatesByQuota(ctx context.Context, maxBytes int64) ([]ThumbnailEvictionCandidatesByQuotaRow, error) {
	rows, err := q.db.Query(ctx, thumbnailEvictionCandidatesByQuota, maxBytes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThumbnailEvictionCandidatesByQuotaRow
	for rows.Next() {
		var i ThumbnailEvictionCandidatesByQuotaRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.RunningBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalThumbnailBytes = `-- name: TotalThumbnailBytes :one
SELECT COALESCE(sum(size_bytes), 0)::bigint FROM thumbnail_cache
`

func (q *Queries) TotalThumbnailBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalThumbnailBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchThumbnail = `-- name: TouchThumbnail :exec
UPDATE thumbnail_cache SET last_access_at = now() WHERE id = $1
`

// TouchThumbnail is the read path's only write. It is separate from
// GetThumbnail so a lookup that misses in the object store does not extend an
// entry's life.
func (q *Queries) TouchThumbnail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchThumbnail, id)
	return err
}

const upsertThumbnail = `-- name: UpsertThumbnail :one

INSERT INTO thumbnail_cache (
    content_version_id, page, width, height, format, object_key, size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (content_version_id, page, width, height, format) DO UPDATE SET
    object_key     = EXCLUDED.object_key,
    size_bytes     = EXCLUDED.size_bytes,
    last_access_at = now()
RETURNING id, content_version_id, page, width, height, format, object_key, size_bytes, created_at, last_access_at
`

type UpsertThumbnailParams struct {
	ContentVersionID int64
	Page             int32
	Width            int32
	Height           int32
	Format           string
	ObjectKey        string
	SizeBytes        int64
}

// Thumbnail cache accounting (D-008). Rows here describe objects in VersityGW;
// every delete returns the object keys the caller still has to remove there.
func (q *Queries) UpsertThumbnail(ctx context.Context, arg UpsertThumbnailParams) (ThumbnailCache, error) {
	row := q.db.QueryRow(ctx, upsertThumbnail,
		arg.ContentVersionID,
		arg.Page,
		arg.Width,
		arg.Height,
		arg.Format,
		arg.ObjectKey,
		arg.SizeBytes,
	)
	var i ThumbnailCache
	err := row.Scan(
		&i.ID,
		&i.ContentVersionID,
		&i.Page,
		&i.Width,
		&i.Height,
		&i.Format,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.LastAccessAt,
	)
	return i, err
}
